/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    FileTree: typeof import('./components/sidebar/FileTree.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    InterimBanner: typeof import('./components/editor/InterimBanner.vue')['default']
    MicButton: typeof import('./components/editor/MicButton.vue')['default']
    ParticipantsList: typeof import('./components/sidebar/ParticipantsList.vue')['default']
    RoomPage: typeof import('./components/RoomPage.vue')['default']
    ShareButton: typeof import('./components/editor/ShareButton.vue')['default']
    Sidebar: typeof import('./components/sidebar/Sidebar.vue')['default']
    TiptapEditor: typeof import('./components/editor/TiptapEditor.vue')['default']
    Toolbar: typeof import('./components/editor/Toolbar.vue')['default']
    TreeNode: typeof import('./components/sidebar/TreeNode.vue')['default']
    UserNameModal: typeof import('./components/common/UserNameModal.vue')['default']
  }
}
