/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  http: {
    Health: () => import('#controllers/http/health_controller'),
    Metrics: () => import('#controllers/http/metrics_controller'),
    RoomInvites: () => import('#controllers/http/room_invites_controller'),
    Rooms: () => import('#controllers/http/rooms_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
