/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorBoundary: typeof import('./shared/components/ErrorBoundary.vue')['default']
    FileTree: typeof import('./features/file-tree/components/FileTree.vue')['default']
    Icon: typeof import('./shared/components/Icon.vue')['default']
    InterimBanner: typeof import('./features/editor/components/InterimBanner.vue')['default']
    MicButton: typeof import('./features/editor/components/MicButton.vue')['default']
    ParticipantsList: typeof import('./features/file-tree/components/ParticipantsList.vue')['default']
    PracticePanel: typeof import('./features/editor/components/PracticePanel.vue')['default']
    ShareButton: typeof import('./features/editor/components/ShareButton.vue')['default']
    Sidebar: typeof import('./features/file-tree/components/Sidebar.vue')['default']
    TiptapEditor: typeof import('./features/editor/components/TiptapEditor.vue')['default']
    Toolbar: typeof import('./features/editor/components/Toolbar.vue')['default']
    TreeNode: typeof import('./features/file-tree/components/TreeNode.vue')['default']
    UserNameModal: typeof import('./shared/components/UserNameModal.vue')['default']
  }
}
